import type { CategorySlug } from "@/lib/data/types";

/** One bookable occasion; each gets its own page at /services/<slug> for local search. */
export interface Service {
  slug: string;
  /** Existing portfolio category used for the photos on the service page */
  category: CategorySlug;
  group: "couples" | "family" | "parties" | "milestones";
  nameDe: string;
  nameEn: string;
  /** Search-style headline, e.g. "Gender Reveal Fotograf in Berlin" */
  titleDe: string;
  titleEn: string;
  shortDe: string;
  shortEn: string;
  bodyDe: string;
  bodyEn: string;
  includesDe: string[];
  includesEn: string[];
  spots: string[];
  faqDe: { q: string; a: string };
  faqEn: { q: string; a: string };
  keywordsDe: string[];
}

export const SERVICE_GROUPS = {
  couples: { de: "Paare & Liebe", en: "Couples & love" },
  family: { de: "Familie & Baby", en: "Family & baby" },
  parties: { de: "Feiern & Partys", en: "Parties & celebrations" },
  milestones: { de: "Meilensteine & Anlässe", en: "Milestones & occasions" },
} as const;

/** Districts and nearby towns the studio covers; used for areaServed and the "where we shoot" section. */
export const BERLIN_AREAS = [
  "Mitte",
  "Kreuzberg",
  "Neukölln",
  "Friedrichshain",
  "Prenzlauer Berg",
  "Charlottenburg",
  "Wilmersdorf",
  "Schöneberg",
  "Tempelhof",
  "Wedding",
  "Moabit",
  "Pankow",
  "Lichtenberg",
  "Treptow",
  "Köpenick",
  "Steglitz",
  "Zehlendorf",
  "Spandau",
  "Reinickendorf",
  "Marzahn-Hellersdorf",
  "Potsdam",
] as const;

const PARKS = ["Tiergarten", "Tempelhofer Feld", "Treptower Park", "Landwehrkanal", "Park am Gleisdreieck", "Viktoriapark"];

export const SERVICES: Service[] = [
  {
    slug: "paarshooting-berlin",
    category: "couples",
    group: "couples",
    nameDe: "Paarshooting",
    nameEn: "Couple photoshoot",
    titleDe: "Paarshooting in Berlin",
    titleEn: "Couple photoshoot in Berlin",
    shortDe: "Entspannte Paarfotos an euren Lieblingsorten in Berlin – natürlich, nah und ohne steifes Posieren.",
    shortEn: "Relaxed couple photos at your favourite places in Berlin – natural, close and never stiff.",
    bodyDe: "Ob goldene Stunde im Tiergarten, Spaziergang am Landwehrkanal oder ein gemütlicher Abend bei euch zu Hause: Wir begleiten euch als Paar und halten fest, wie ihr miteinander seid. Wir geben sanfte Impulse statt starrer Posen, damit die Bilder nach euch aussehen.",
    bodyEn: "Golden hour in Tiergarten, a walk along the Landwehrkanal or a cosy evening at home: we follow you as a couple and capture how you really are together. Gentle prompts instead of stiff poses, so the photos look like you.",
    includesDe: ["1–2 Stunden an einem oder zwei Orten", "Vorgespräch zu Ort, Outfit und Stimmung", "Bearbeitete Online-Galerie in hoher Auflösung"],
    includesEn: ["1–2 hours at one or two locations", "Planning chat about place, outfits and mood", "Edited high-resolution online gallery"],
    spots: PARKS,
    faqDe: { q: "Wir sind kamerascheu – klappt das trotzdem?", a: "Auf jeden Fall. Die meisten Paare sind am Anfang nervös. Nach zehn Minuten Spaziergang vergessen die meisten die Kamera." },
    faqEn: { q: "We're camera-shy – will it still work?", a: "Absolutely. Most couples are nervous at first; after ten minutes of walking most forget the camera is there." },
    keywordsDe: ["Paarshooting Berlin", "Pärchen Fotoshooting Berlin", "Couple Fotograf Berlin", "Liebesfotos Berlin"],
  },
  {
    slug: "verlobungsshooting-berlin",
    category: "couples",
    group: "couples",
    nameDe: "Verlobungsshooting",
    nameEn: "Engagement shoot",
    titleDe: "Verlobungsshooting in Berlin",
    titleEn: "Engagement photoshoot in Berlin",
    shortDe: "Feiert eure Verlobung mit Bildern für Save-the-Date-Karten, Social Media und euer Zuhause.",
    shortEn: "Celebrate your engagement with photos for save-the-dates, social media and your walls.",
    bodyDe: "Ihr habt Ja gesagt – jetzt gehören die Fotos dazu. Beim Verlobungsshooting zeigen wir euch so, wie ihr gerade seid: aufgeregt, verliebt, voller Pläne. Die Bilder eignen sich perfekt für Save-the-Date-Karten und Hochzeitswebsites.",
    bodyEn: "You said yes – now come the photos. An engagement shoot shows you exactly as you are right now: excited, in love, full of plans. Perfect for save-the-date cards and wedding websites.",
    includesDe: ["1–2 Stunden Shooting", "Hilfe bei der Ortswahl in Berlin", "Bilder auch im Querformat für Karten"],
    includesEn: ["1–2 hour session", "Help choosing a Berlin location", "Images in landscape for cards too"],
    spots: ["Museumsinsel", "Gendarmenmarkt", ...PARKS.slice(0, 3)],
    faqDe: { q: "Wann sollte das Verlobungsshooting stattfinden?", a: "Idealerweise 6–12 Monate vor der Hochzeit, damit die Bilder rechtzeitig für Save-the-Date-Karten fertig sind." },
    faqEn: { q: "When should we do the engagement shoot?", a: "Ideally 6–12 months before the wedding so the images are ready in time for save-the-date cards." },
    keywordsDe: ["Verlobungsshooting Berlin", "Engagement Shooting Berlin", "Save the Date Fotos Berlin"],
  },
  {
    slug: "heiratsantrag-fotograf-berlin",
    category: "couples",
    group: "couples",
    nameDe: "Heiratsantrag",
    nameEn: "Proposal photography",
    titleDe: "Heiratsantrag fotografieren lassen in Berlin",
    titleEn: "Proposal photographer in Berlin",
    shortDe: "Wir verstecken uns, du stellst die Frage – und der Moment ist für immer festgehalten.",
    shortEn: "We hide, you pop the question – and the moment is captured forever.",
    bodyDe: "Ein Heiratsantrag passiert nur einmal. Wir planen mit dir Ort, Timing und Versteck, bleiben unsichtbar bis zum großen Moment und fotografieren danach noch ein kurzes Paarshooting – während ihr beide noch strahlt.",
    bodyEn: "A proposal happens once. We plan the place, timing and hiding spot with you, stay invisible until the big moment, then shoot a short couple session while you're both still glowing.",
    includesDe: ["Geheime Planung per WhatsApp", "Diskrete Begleitung vor Ort", "Kurzes Paarshooting direkt danach"],
    includesEn: ["Secret planning via WhatsApp", "Discreet coverage on site", "Short couple session right after"],
    spots: ["Oberbaumbrücke", "Berliner Dom", "Tiergarten", "Fernsehturm-Umgebung"],
    faqDe: { q: "Wie bleibt der Antrag eine Überraschung?", a: "Wir sprechen nur mit dir, kommen getrennt an und sehen aus wie Touristen mit Kamera – bis zum Ja." },
    faqEn: { q: "How do you keep it a surprise?", a: "We only talk to you, arrive separately and look like tourists with a camera – until the yes." },
    keywordsDe: ["Heiratsantrag Fotograf Berlin", "Antrag fotografieren Berlin", "Proposal Fotograf Berlin"],
  },
  {
    slug: "standesamt-fotograf-berlin",
    category: "couples",
    group: "couples",
    nameDe: "Standesamtliche Trauung",
    nameEn: "Civil wedding",
    titleDe: "Fotograf für die standesamtliche Trauung in Berlin",
    titleEn: "Civil wedding photographer in Berlin",
    shortDe: "Kleine Hochzeit, große Gefühle: Trauung, Gratulationen und Paarfotos am Standesamt.",
    shortEn: "Small wedding, big feelings: ceremony, congratulations and couple portraits at the registry office.",
    bodyDe: "Für standesamtliche Hochzeiten in Berlin – vom Rathaus Schöneberg bis zum Standesamt Mitte – begleiten wir Trauung, Sektempfang und ein kurzes Paarshooting in der Umgebung. Ideal für kleine Hochzeiten und Hochzeiten im engsten Kreis.",
    bodyEn: "For civil weddings across Berlin – from Rathaus Schöneberg to the Mitte registry office – we cover the ceremony, the toast and a short couple session nearby. Ideal for small and intimate weddings.",
    includesDe: ["Trauung und Gratulationen", "Gruppenfotos mit Familie und Freunden", "Paarfotos in der Umgebung"],
    includesEn: ["Ceremony and congratulations", "Group photos with family and friends", "Couple portraits nearby"],
    spots: ["Rathaus Schöneberg", "Standesamt Mitte", "Rotes Rathaus", "Schloss Charlottenburg"],
    faqDe: { q: "Fotografiert ihr auch große Hochzeiten?", a: "Wir sind auf kleine, persönliche Feiern spezialisiert – Standesamt und Hochzeiten bis etwa 50 Gäste." },
    faqEn: { q: "Do you photograph big weddings?", a: "We specialise in small, personal celebrations – registry weddings and weddings up to about 50 guests." },
    keywordsDe: ["Standesamt Fotograf Berlin", "Hochzeitsfotograf Standesamt Berlin", "kleine Hochzeit Fotograf Berlin"],
  },
  {
    slug: "jahrestag-fotoshooting-berlin",
    category: "couples",
    group: "couples",
    nameDe: "Jahrestag & Hochzeitstag",
    nameEn: "Anniversary shoot",
    titleDe: "Fotoshooting zum Jahrestag in Berlin",
    titleEn: "Anniversary photoshoot in Berlin",
    shortDe: "Ein Jahr, zehn Jahre, fünfzig Jahre – feiert eure Geschichte mit neuen Bildern.",
    shortEn: "One year, ten years, fifty years – celebrate your story with new photos.",
    bodyDe: "Ob erster Jahrestag oder Goldene Hochzeit: Ein Shooting ist ein Geschenk, das bleibt. Gern an dem Ort, an dem alles anfing – das Café des ersten Dates oder der Park des ersten Kusses.",
    bodyEn: "First anniversary or golden wedding: a shoot is a gift that lasts. Ideally where it all began – the café of your first date or the park of your first kiss.",
    includesDe: ["Shooting am Ort mit Bedeutung", "Auch als Gutschein verschenkbar", "Bearbeitete Online-Galerie"],
    includesEn: ["Session at a meaningful place", "Can be given as a gift voucher", "Edited online gallery"],
    spots: PARKS,
    faqDe: { q: "Kann ich ein Shooting verschenken?", a: "Ja, schreib uns auf WhatsApp – wir erstellen einen persönlichen Gutschein." },
    faqEn: { q: "Can I give a shoot as a gift?", a: "Yes, message us on WhatsApp and we'll create a personal voucher." },
    keywordsDe: ["Jahrestag Fotoshooting Berlin", "Hochzeitstag Fotoshooting", "Fotoshooting verschenken Berlin"],
  },
  {
    slug: "gender-reveal-fotograf-berlin",
    category: "gender-reveal",
    group: "family",
    nameDe: "Gender Reveal",
    nameEn: "Gender reveal",
    titleDe: "Gender Reveal Fotograf in Berlin",
    titleEn: "Gender reveal photographer in Berlin",
    shortDe: "Rosa oder Blau? Wir fangen die Spannung, den Moment und jede Reaktion ein.",
    shortEn: "Pink or blue? We capture the build-up, the moment and every reaction.",
    bodyDe: "Ballon, Konfetti, Torte oder Rauch – der Gender-Reveal-Moment dauert nur Sekunden. Wir positionieren uns vorher, fotografieren in Serie und halten auch die Gesichter eurer Familie und Freunde fest. Drinnen oder draußen, im Park oder im Garten.",
    bodyEn: "Balloon, confetti, cake or smoke – the reveal lasts seconds. We position ourselves in advance, shoot in bursts and catch the faces of your family and friends too. Indoors or outdoors, in a park or a garden.",
    includesDe: ["Vorbereitung, Reveal und Feier danach", "Reaktionen der Gäste", "Schnelle Vorschau zum Teilen"],
    includesEn: ["Set-up, reveal and party after", "Guests' reactions", "Quick sneak peek to share"],
    spots: PARKS,
    faqDe: { q: "Wie lange dauert ein Gender-Reveal-Shooting?", a: "Meist 1,5–2 Stunden – genug für Vorbereitung, den Moment selbst und Gruppenfotos." },
    faqEn: { q: "How long is a gender reveal shoot?", a: "Usually 1.5–2 hours – enough for set-up, the moment itself and group photos." },
    keywordsDe: ["Gender Reveal Fotograf Berlin", "Gender Reveal Party Berlin", "Gender Reveal Fotoshooting"],
  },
  {
    slug: "babyparty-fotograf-berlin",
    category: "gender-reveal",
    group: "family",
    nameDe: "Babyparty",
    nameEn: "Baby shower",
    titleDe: "Babyparty Fotograf in Berlin",
    titleEn: "Baby shower photographer in Berlin",
    shortDe: "Deko, Spiele, Geschenke und die werdende Mama im Mittelpunkt – liebevoll fotografiert.",
    shortEn: "Decor, games, gifts and the mum-to-be at the centre – lovingly photographed.",
    bodyDe: "Eine Babyparty steckt voller kleiner Details und großer Gefühle. Wir fotografieren Deko und Buffet, die Spiele, das Auspacken der Geschenke und natürlich Porträts der werdenden Eltern.",
    bodyEn: "A baby shower is full of small details and big emotions. We photograph the decor and food, the games, the gift opening and of course portraits of the parents-to-be.",
    includesDe: ["Detail- und Dekofotos", "Spiele und Geschenke", "Porträts der werdenden Eltern"],
    includesEn: ["Detail and decor shots", "Games and gifts", "Portraits of the parents-to-be"],
    spots: ["Zuhause", "Café oder Restaurant", "Gemieteter Raum", "Garten"],
    faqDe: { q: "Kann man Babyparty und Babybauch-Shooting kombinieren?", a: "Ja, gern – wir planen dann 30 Minuten extra für Babybauch-Porträts ein." },
    faqEn: { q: "Can we combine the baby shower with a maternity shoot?", a: "Yes – we simply add 30 minutes for maternity portraits." },
    keywordsDe: ["Babyparty Fotograf Berlin", "Baby Shower Berlin Fotos", "Babyshower Fotograf"],
  },
  {
    slug: "babybauch-shooting-berlin",
    category: "couples",
    group: "family",
    nameDe: "Babybauch-Shooting",
    nameEn: "Maternity shoot",
    titleDe: "Babybauch-Shooting in Berlin",
    titleEn: "Maternity photoshoot in Berlin",
    shortDe: "Schwangerschaftsfotos im Park, im Licht eurer Wohnung oder am Wasser – natürlich und warm.",
    shortEn: "Pregnancy photos in a park, the light of your home or by the water – natural and warm.",
    bodyDe: "Die Schwangerschaft ist eine kurze, besondere Zeit. Am schönsten sind Babybauch-Fotos zwischen der 28. und 34. Woche. Gern mit Partner, Geschwisterkind oder Haustier – ganz ohne Studio-Steifheit.",
    bodyEn: "Pregnancy is a short, special time. Maternity photos are loveliest between weeks 28 and 34. With partner, sibling or pet if you like – none of the studio stiffness.",
    includesDe: ["Ca. 1 Stunde in ruhigem Tempo", "Mit Partner und Familie möglich", "Outfit-Tipps vorab"],
    includesEn: ["About 1 hour at a gentle pace", "Partner and family welcome", "Outfit tips beforehand"],
    spots: ["Zuhause", ...PARKS.slice(0, 3)],
    faqDe: { q: "Wann ist der beste Zeitpunkt für Babybauchfotos?", a: "Meist zwischen der 28. und 34. Schwangerschaftswoche – der Bauch ist schön rund und es ist noch bequem." },
    faqEn: { q: "When is the best time for maternity photos?", a: "Usually between weeks 28 and 34 – the bump is round and it's still comfortable." },
    keywordsDe: ["Babybauch Shooting Berlin", "Schwangerschaftsfotos Berlin", "Babybauchfotograf Berlin"],
  },
  {
    slug: "familienshooting-berlin",
    category: "gatherings",
    group: "family",
    nameDe: "Familienshooting",
    nameEn: "Family photoshoot",
    titleDe: "Familienshooting in Berlin",
    titleEn: "Family photoshoot in Berlin",
    shortDe: "Echte Familienfotos statt Studiolächeln – beim Spielen im Park oder zu Hause.",
    shortEn: "Real family photos instead of studio smiles – playing in the park or at home.",
    bodyDe: "Kinder posieren nicht gern – müssen sie auch nicht. Wir lassen eure Familie spielen, toben und kuscheln und fotografieren dabei die Momente, die ihr in zehn Jahren sehen wollt. Gern mit Großeltern.",
    bodyEn: "Kids don't like posing – and they don't have to. We let your family play, run around and cuddle and photograph the moments you'll want to see in ten years. Grandparents welcome.",
    includesDe: ["1–1,5 Stunden draußen oder zu Hause", "Geduld für die Kleinen", "Einzel-, Geschwister- und Gruppenfotos"],
    includesEn: ["1–1.5 hours outdoors or at home", "Patience for the little ones", "Individual, sibling and group photos"],
    spots: PARKS,
    faqDe: { q: "Was, wenn unser Kind keine Lust hat?", a: "Ganz normal. Wir machen Pausen, spielen mit und fotografieren, was passiert – oft werden das die schönsten Bilder." },
    faqEn: { q: "What if our child isn't in the mood?", a: "Totally normal. We take breaks, play along and photograph what happens – often those are the best pictures." },
    keywordsDe: ["Familienshooting Berlin", "Familienfotograf Berlin", "Familienfotos draußen Berlin"],
  },
  {
    slug: "taufe-fotograf-berlin",
    category: "gatherings",
    group: "family",
    nameDe: "Taufe & Namensfeier",
    nameEn: "Christening & naming day",
    titleDe: "Fotograf für Taufe und Namensfeier in Berlin",
    titleEn: "Christening & naming day photographer in Berlin",
    shortDe: "Zeremonie, Familie und Feier danach – ruhig und respektvoll begleitet.",
    shortEn: "Ceremony, family and celebration – covered calmly and respectfully.",
    bodyDe: "Ob kirchliche Taufe, freie Namensfeier oder Willkommensfest: Wir fotografieren die Zeremonie unauffällig, ohne Blitz in der Kirche, und begleiten danach das Familienfest mit Gruppenfotos aller Generationen.",
    bodyEn: "Church christening, secular naming day or welcome party: we photograph the ceremony discreetly, without flash in church, then cover the family celebration with multi-generation group shots.",
    includesDe: ["Zeremonie ohne Blitz", "Familien- und Generationenfotos", "Feier, Torte und Details"],
    includesEn: ["Flash-free ceremony coverage", "Family and generation photos", "Party, cake and details"],
    spots: ["Kirche", "Restaurant", "Zuhause", "Garten"],
    faqDe: { q: "Dürft ihr in der Kirche fotografieren?", a: "Wir klären das vorab mit der Gemeinde und halten uns an alle Regeln – meist ist Fotografieren ohne Blitz erlaubt." },
    faqEn: { q: "Are you allowed to photograph in church?", a: "We check with the parish beforehand and follow their rules – flash-free photography is usually allowed." },
    keywordsDe: ["Taufe Fotograf Berlin", "Tauffotograf Berlin", "Namensfeier Fotograf"],
  },
  {
    slug: "geburtstag-fotograf-berlin",
    category: "birthdays",
    group: "parties",
    nameDe: "Geburtstag",
    nameEn: "Birthday party",
    titleDe: "Fotograf für Geburtstagsfeiern in Berlin",
    titleEn: "Birthday party photographer in Berlin",
    shortDe: "Deine Party, deine Leute – wir fotografieren, du feierst.",
    shortEn: "Your party, your people – we shoot, you celebrate.",
    bodyDe: "Von der Dinnerparty bis zur Feier im Club-Hinterzimmer: Wir dokumentieren Gäste, Reden, Torte und Tanzfläche und sorgen dafür, dass du am Ende nicht nur verwackelte Handyfotos hast.",
    bodyEn: "From dinner party to club back room: we document guests, speeches, cake and dance floor, so you end up with more than blurry phone pics.",
    includesDe: ["2–4 Stunden Begleitung", "Gäste, Details und Highlights", "Gruppenfotos mit allen"],
    includesEn: ["2–4 hours coverage", "Guests, details and highlights", "Group photos with everyone"],
    spots: ["Restaurant", "Bar", "Zuhause", "Eventlocation"],
    faqDe: { q: "Fotografiert ihr auch abends und bei wenig Licht?", a: "Ja, wir arbeiten mit lichtstarken Objektiven und dezentem Blitz, damit die Stimmung erhalten bleibt." },
    faqEn: { q: "Do you shoot in the evening and low light?", a: "Yes, we use fast lenses and subtle flash so the atmosphere stays intact." },
    keywordsDe: ["Geburtstag Fotograf Berlin", "Partyfotograf Berlin", "Eventfotograf Geburtstag Berlin"],
  },
  {
    slug: "kindergeburtstag-fotograf-berlin",
    category: "kids",
    group: "parties",
    nameDe: "Kindergeburtstag",
    nameEn: "Kids' birthday party",
    titleDe: "Kindergeburtstag fotografieren lassen in Berlin",
    titleEn: "Kids' birthday party photographer in Berlin",
    shortDe: "Kerzen auspusten, Geschenke, Chaos und Freude – ehrlich festgehalten.",
    shortEn: "Blowing out candles, presents, chaos and joy – captured honestly.",
    bodyDe: "Beim Kindergeburtstag sind Eltern mit Organisieren beschäftigt – wir übernehmen die Fotos. Wir bewegen uns auf Augenhöhe der Kinder, fotografieren Spiele, Kuchen und den Kerzenmoment und bleiben dabei geduldig.",
    bodyEn: "At kids' parties parents are busy organising – we take care of the photos. We work at the children's eye level, photograph games, cake and the candle moment, and stay patient throughout.",
    includesDe: ["2–3 Stunden Begleitung", "Kerzen- und Geschenkmomente", "Fotos auf Augenhöhe der Kinder"],
    includesEn: ["2–3 hours coverage", "Candle and present moments", "Photos at children's eye level"],
    spots: ["Zuhause", "Indoor-Spielplatz", "Park", "Kindercafé"],
    faqDe: { q: "Ab welchem Alter lohnt sich ein Fotograf?", a: "Vom ersten Geburtstag bis zur Teenager-Party – besonders der 1. Geburtstag und runde Geburtstage werden gern gebucht." },
    faqEn: { q: "From what age is a photographer worth it?", a: "From the first birthday to teen parties – first birthdays and round numbers are especially popular." },
    keywordsDe: ["Kindergeburtstag Fotograf Berlin", "Kinderfotograf Berlin Party", "1. Geburtstag Fotoshooting Berlin"],
  },
  {
    slug: "runder-geburtstag-fotograf-berlin",
    category: "birthdays",
    group: "parties",
    nameDe: "Runder Geburtstag",
    nameEn: "Milestone birthday",
    titleDe: "Fotograf für runde Geburtstage in Berlin",
    titleEn: "Milestone birthday photographer in Berlin",
    shortDe: "18, 30, 40, 50, 60, 70 – große Zahlen verdienen große Erinnerungen.",
    shortEn: "18, 30, 40, 50, 60, 70 – big numbers deserve big memories.",
    bodyDe: "Ein runder Geburtstag bringt oft Menschen zusammen, die sich selten sehen. Wir sorgen dafür, dass jeder Gast, jede Rede und jedes Wiedersehen festgehalten wird – inklusive großem Gruppenfoto.",
    bodyEn: "Milestone birthdays often bring together people who rarely meet. We make sure every guest, speech and reunion is captured – including the big group photo.",
    includesDe: ["Reden und Überraschungen", "Fotos aller Gäste", "Großes Gruppenfoto"],
    includesEn: ["Speeches and surprises", "Photos of every guest", "Big group photo"],
    spots: ["Restaurant", "Eventlocation", "Garten", "Zuhause"],
    faqDe: { q: "Könnt ihr auch eine Überraschungsparty fotografieren?", a: "Sehr gern – wir stimmen uns heimlich mit den Organisatoren ab und sind beim großen Moment bereit." },
    faqEn: { q: "Can you photograph a surprise party?", a: "Gladly – we coordinate secretly with the organisers and are ready for the big moment." },
    keywordsDe: ["runder Geburtstag Fotograf Berlin", "50. Geburtstag Fotograf", "30. Geburtstag Fotos Berlin"],
  },
  {
    slug: "jga-fotograf-berlin",
    category: "gatherings",
    group: "parties",
    nameDe: "Junggesellinnenabschied",
    nameEn: "Hen & stag party",
    titleDe: "JGA-Fotoshooting in Berlin",
    titleEn: "Hen & stag party photoshoot in Berlin",
    shortDe: "Euer JGA in Berlin – mit Fotos, die man später gern zeigt.",
    shortEn: "Your hen or stag party in Berlin – with photos you'll actually want to show.",
    bodyDe: "Berlin ist eine der beliebtesten JGA-Städte. Wir begleiten eure Gruppe bei einem Fotospaziergang durch Kreuzberg, an der East Side Gallery oder beim Brunch – lustig, stilvoll und ohne peinliche Momente.",
    bodyEn: "Berlin is one of the most popular hen and stag destinations. We join your group for a photo walk through Kreuzberg, at the East Side Gallery or over brunch – fun, stylish and nothing embarrassing.",
    includesDe: ["1–2 Stunden Gruppen-Fotospaziergang", "Ideen für Spots und Gruppenbilder", "Schnelle Lieferung für Social Media"],
    includesEn: ["1–2 hour group photo walk", "Ideas for spots and group shots", "Fast delivery for social media"],
    spots: ["East Side Gallery", "Oberbaumbrücke", "Kreuzberg", "Brandenburger Tor"],
    faqDe: { q: "Wie groß darf die Gruppe sein?", a: "Bis etwa 20 Personen klappt ein Fotospaziergang sehr gut." },
    faqEn: { q: "How big can the group be?", a: "Up to about 20 people works well for a photo walk." },
    keywordsDe: ["JGA Fotoshooting Berlin", "Junggesellinnenabschied Berlin Fotograf", "JGA Berlin Fotos"],
  },
  {
    slug: "dinnerparty-fotograf-berlin",
    category: "gatherings",
    group: "parties",
    nameDe: "Dinner & private Feiern",
    nameEn: "Dinners & private parties",
    titleDe: "Fotograf für private Feiern und Dinner in Berlin",
    titleEn: "Private party & dinner photographer in Berlin",
    shortDe: "Supper Club, Hauseinweihung oder Sommerfest – stimmungsvoll dokumentiert.",
    shortEn: "Supper club, housewarming or summer party – beautifully documented.",
    bodyDe: "Lange Tafeln, Kerzenlicht, gute Gespräche: Private Feiern leben von Atmosphäre. Wir fotografieren Tischdeko, Essen und Gäste so, wie sich der Abend angefühlt hat.",
    bodyEn: "Long tables, candlelight, good conversations: private parties live on atmosphere. We photograph table settings, food and guests the way the evening felt.",
    includesDe: ["Atmosphäre und Details", "Gäste und Gespräche", "Flexible Dauer"],
    includesEn: ["Atmosphere and details", "Guests and conversations", "Flexible duration"],
    spots: ["Zuhause", "Restaurant", "Dachterrasse", "Garten"],
    faqDe: { q: "Stört ein Fotograf beim Dinner?", a: "Nein – wir arbeiten leise und unauffällig. Die meisten Gäste merken uns nach kurzer Zeit kaum noch." },
    faqEn: { q: "Is a photographer disruptive at dinner?", a: "No – we work quietly and unobtrusively. Most guests barely notice us after a while." },
    keywordsDe: ["Eventfotograf Berlin privat", "Fotograf private Feier Berlin", "Hauseinweihung Fotograf"],
  },
  {
    slug: "firmenfeier-fotograf-berlin",
    category: "gatherings",
    group: "parties",
    nameDe: "Firmenfeier & Teamevent",
    nameEn: "Company & team events",
    titleDe: "Fotograf für Firmenfeiern und Teamevents in Berlin",
    titleEn: "Company party & team event photographer in Berlin",
    shortDe: "Weihnachtsfeier, Sommerfest oder Jubiläum – für Kleinunternehmen und Teams.",
    shortEn: "Christmas party, summer party or anniversary – for small businesses and teams.",
    bodyDe: "Für Start-ups, Agenturen und kleine Unternehmen in Berlin fotografieren wir Teamevents, Weihnachtsfeiern und Firmenjubiläen – locker im Stil, nutzbar für Website, LinkedIn und Recruiting.",
    bodyEn: "For start-ups, agencies and small businesses in Berlin we photograph team events, Christmas parties and company anniversaries – relaxed in style, usable for your website, LinkedIn and recruiting.",
    includesDe: ["Event- und Teamfotos", "Bilder für Website und LinkedIn", "Rechnung für Unternehmen"],
    includesEn: ["Event and team photos", "Images for website and LinkedIn", "Business invoice"],
    spots: ["Büro", "Eventlocation", "Restaurant", "Dachterrasse"],
    faqDe: { q: "Dürfen wir die Fotos geschäftlich nutzen?", a: "Ja, die Nutzungsrechte für eure eigenen Kanäle sind inklusive." },
    faqEn: { q: "Can we use the photos commercially?", a: "Yes, usage rights for your own channels are included." },
    keywordsDe: ["Firmenfeier Fotograf Berlin", "Weihnachtsfeier Fotograf Berlin", "Teamevent Fotograf Berlin"],
  },
  {
    slug: "henna-abend-fotograf-berlin",
    category: "gatherings",
    group: "milestones",
    nameDe: "Henna-Abend & kulturelle Feste",
    nameEn: "Henna night & cultural celebrations",
    titleDe: "Fotograf für Henna-Abend und kulturelle Feste in Berlin",
    titleEn: "Henna night & cultural celebration photographer in Berlin",
    shortDe: "Kına, Verlobungsfeier, Eid oder Familienfest – mit Respekt für eure Traditionen.",
    shortEn: "Kına, engagement party, Eid or family festival – with respect for your traditions.",
    bodyDe: "Berlin feiert in vielen Sprachen. Wir fotografieren Henna-Abende, traditionelle Verlobungen und kulturelle Familienfeste und achten auf die Rituale, Gewänder und Momente, die euch wichtig sind. Wir sprechen Deutsch und Englisch.",
    bodyEn: "Berlin celebrates in many languages. We photograph henna nights, traditional engagements and cultural family celebrations, paying attention to the rituals, outfits and moments that matter to you. We speak German and English.",
    includesDe: ["Vorgespräch zu Ablauf und Ritualen", "Tänze, Zeremonie und Familie", "Lange Feiern möglich"],
    includesEn: ["Planning chat about schedule and rituals", "Dances, ceremony and family", "Long celebrations possible"],
    spots: ["Festsaal", "Restaurant", "Zuhause", "Eventlocation"],
    faqDe: { q: "Kennt ihr den Ablauf unserer Tradition?", a: "Wir fragen vorab genau nach – welche Momente wichtig sind und wer unbedingt aufs Bild muss." },
    faqEn: { q: "Do you know how our tradition works?", a: "We ask in detail beforehand – which moments matter and who must be in the photos." },
    keywordsDe: ["Henna Abend Fotograf Berlin", "Kına Gecesi Fotograf Berlin", "Verlobungsfeier Fotograf Berlin"],
  },
  {
    slug: "einschulung-fotograf-berlin",
    category: "kids",
    group: "milestones",
    nameDe: "Einschulung",
    nameEn: "First day of school",
    titleDe: "Einschulung fotografieren lassen in Berlin",
    titleEn: "First day of school photos in Berlin",
    shortDe: "Schultüte, großer Tag, kleine Helden – Fotos für die ganze Familie.",
    shortEn: "School cone, big day, little heroes – photos for the whole family.",
    bodyDe: "Die Einschulung ist ein Meilenstein. Wir fotografieren dein Kind mit Schultüte, die Familie vor der Schule und das Fest danach – entspannt, ohne Stress am großen Morgen.",
    bodyEn: "Starting school is a milestone. We photograph your child with their school cone, the family in front of the school and the celebration after – relaxed, no stress on the big morning.",
    includesDe: ["Porträts mit Schultüte", "Familienfotos", "Optional die Feier danach"],
    includesEn: ["Portraits with the school cone", "Family photos", "Optionally the party after"],
    spots: ["Vor der Schule", "Park", "Zuhause"],
    faqDe: { q: "Geht das auch vor oder nach dem Tag?", a: "Ja – viele Familien machen das Schultüten-Shooting ein paar Tage vorher im Park, ganz ohne Zeitdruck." },
    faqEn: { q: "Can we do it before or after the day?", a: "Yes – many families do the school-cone shoot a few days earlier in a park, without any time pressure." },
    keywordsDe: ["Einschulung Fotograf Berlin", "Schultüte Fotoshooting Berlin", "Einschulungsfotos Berlin"],
  },
  {
    slug: "abschluss-fotoshooting-berlin",
    category: "gatherings",
    group: "milestones",
    nameDe: "Abschluss & Abiball",
    nameEn: "Graduation",
    titleDe: "Abschluss- und Abiball-Fotoshooting in Berlin",
    titleEn: "Graduation photoshoot in Berlin",
    shortDe: "Abi, Bachelor, Master – feiert den Abschluss mit Porträts und Freunden.",
    shortEn: "High school, bachelor's, master's – celebrate with portraits and friends.",
    bodyDe: "Jahre Arbeit, ein Tag zum Feiern: Wir fotografieren Absolventinnen und Absolventen mit Familie und Freunden – vor der Uni, im Park oder beim Abiball.",
    bodyEn: "Years of work, one day to celebrate: we photograph graduates with family and friends – in front of the university, in a park or at the prom.",
    includesDe: ["Einzelporträts", "Fotos mit Familie und Freunden", "Auch für kleine Gruppen buchbar"],
    includesEn: ["Individual portraits", "Photos with family and friends", "Bookable for small groups"],
    spots: ["Humboldt-Universität", "Freie Universität", "Technische Universität", "Tiergarten"],
    faqDe: { q: "Können sich Freunde ein Shooting teilen?", a: "Ja, Gruppen von 2–6 Absolventen können ein gemeinsames Shooting buchen." },
    faqEn: { q: "Can friends share a session?", a: "Yes, groups of 2–6 graduates can book a shared session." },
    keywordsDe: ["Abschluss Fotoshooting Berlin", "Abiball Fotograf Berlin", "Graduation Fotos Berlin"],
  },
  {
    slug: "outdoor-fotoshooting-berlin",
    category: "outdoor",
    group: "milestones",
    nameDe: "Outdoor-Shooting & Porträts",
    nameEn: "Outdoor portraits",
    titleDe: "Outdoor-Fotoshooting in Berlin",
    titleEn: "Outdoor photoshoot in Berlin",
    shortDe: "Porträts für dich, deine Freunde oder Social Media – an Berlins schönsten Orten.",
    shortEn: "Portraits for you, your friends or social media – at Berlin's most beautiful places.",
    bodyDe: "Kein Anlass nötig: Ein Outdoor-Shooting mit Freundinnen, für dein Profil oder einfach für dich. Wir kennen die schönsten Spots der Stadt und das beste Licht zu jeder Jahreszeit.",
    bodyEn: "No occasion needed: an outdoor shoot with friends, for your profile or just for you. We know the city's best spots and the best light in every season.",
    includesDe: ["Spot-Empfehlungen je nach Jahreszeit", "Mehrere Looks möglich", "Social-Media-taugliche Formate"],
    includesEn: ["Spot suggestions by season", "Several looks possible", "Social-media-ready formats"],
    spots: ["Museumsinsel", "East Side Gallery", "Tempelhofer Feld", "Schloss Charlottenburg", "Tiergarten"],
    faqDe: { q: "Was passiert bei schlechtem Wetter?", a: "Wir verschieben kostenlos oder weichen an überdachte Orte aus." },
    faqEn: { q: "What happens in bad weather?", a: "We reschedule free of charge or move to covered spots." },
    keywordsDe: ["Outdoor Fotoshooting Berlin", "Fotoshooting Berlin draußen", "Porträtfotograf Berlin"],
  },
];

export function getService(slug: string) {
  return SERVICES.find((s) => s.slug === slug);
}

export function serviceName(s: Service, locale: "de" | "en") {
  return locale === "de" ? s.nameDe : s.nameEn;
}
